export type CampaignStatus = "Bozza" | "In lavorazione" | "Da approvare" | "Approvata" | "Inviata a Figma" | "Completata";

export type Campaign = {
  id: string;
  slug: string;
  name: string;
  status: CampaignStatus;
  updated: string;
  category: string;
  type: string;
  thumbnail: string;
  shortDescription: string;
  request: string;
  deliverables: string[];
  date: string;
  attachments: string[];
  figma: boolean;
  background: string;
  offer: string;
  target: string;
  benefits: string;
  visual: { selected: string; variants: string[]; library: string[] };
  visuals: string[];
  copy: { headline: string; subheadline: string; cta: string; price: string; disclaimer: string };
  formats: { name: string; progress: number; status: string; warning?: string; figma?: string }[];
  activity: string[];
};

const img = (n: number) => `https://picsum.photos/seed/ultradisplay-${n}/640/420`;

export const campaigns: Campaign[] = [
  { id: "camp-001", slug: "fibra-24-90", name: "Fibra 24,90", status: "In lavorazione", updated: "2026-07-15", category: "Acquisition", type: "Acquisition", thumbnail: img(1), shortDescription: "Offerta fibra casa con prezzo entry e installazione guidata.", request: "Lancio offerta fibra casa con prezzo entry e installazione semplice.", deliverables: ["Hero web", "Display 300x250", "Stories"], date: "2026-07-22", attachments: ["brief-fibra.pdf"], figma: true, background: "La fibra resta il principale driver per nuove attivazioni domestiche.", offer: "Fibra fino a 1 Gbps a 24,90€ al mese.", target: "Famiglie e smart worker in aree urbane.", benefits: "Connessione stabile, modem incluso, attivazione guidata.", visual: { selected: img(1), variants: [img(1), img(7)], library: ["Living fibra", "Casa smart", "Modem hero"] }, visuals: [img(1), img(7)], copy: { headline: "Fibra ultraveloce a 24,90€", subheadline: "Porta a casa una connessione stabile per tutta la famiglia.", cta: "Scopri l’offerta", price: "24,90€/mese", disclaimer: "Offerta soggetta a copertura tecnica." }, formats: [{ name: "300x250", progress: 100, status: "Pronto", figma: "Figma #FD-2490" }, { name: "728x90", progress: 70, status: "In revisione", warning: "Copy da accorciare" }, { name: "1080x1920", progress: 45, status: "Bloccato", warning: "Visual mancante" }], activity: ["Copy hero aggiornato", "Visual living selezionato", "Formato 300x250 inviato"] },
  { id: "camp-002", slug: "passa-a-tim", name: "Passa a TIM", status: "Da approvare", updated: "2026-07-14", category: "Mobile", type: "Mobile", thumbnail: img(2), shortDescription: "Portabilità mobile con focus su semplicità e copertura.", request: "Campagna portabilità mobile con focus semplicità.", deliverables: ["Social", "Display"], date: "2026-07-20", attachments: ["listino.xlsx"], figma: false, background: "La portabilità richiede messaggi chiari e rassicuranti.", offer: "Minuti, SMS e giga per nuovi clienti mobile.", target: "Utenti competitor sensibili a copertura e prezzo.", benefits: "Rete affidabile, cambio operatore assistito.", visual: { selected: img(2), variants: [img(2)], library: ["Ritratto mobile", "SIM pack"] }, visuals: [img(2)], copy: { headline: "Passa a TIM senza pensieri", subheadline: "Porta il tuo numero e naviga sulla rete TIM.", cta: "Attiva ora", price: "da 9,99€/mese", disclaimer: "Verifica condizioni e copertura." }, formats: [{ name: "300x600", progress: 100, status: "Pronto" }, { name: "320x50", progress: 80, status: "Da approvare" }], activity: ["Checklist legale completata", "CTA aggiornata"] },
  { id: "camp-003", slug: "timvision-estate", name: "TIMVISION Estate", status: "Approvata", updated: "2026-07-10", category: "Entertainment", type: "Entertainment", thumbnail: img(3), shortDescription: "Bundle contenuti e intrattenimento per il periodo estivo.", request: "Promuovere intrattenimento estivo e bundle contenuti.", deliverables: ["Landing", "DEM"], date: "2026-07-28", attachments: [], figma: true, background: "Estate come momento di consumo contenuti condiviso.", offer: "TIMVISION con cinema, serie e sport.", target: "Famiglie e appassionati entertainment.", benefits: "Tanti contenuti in un’unica esperienza.", visual: { selected: img(3), variants: [img(3), img(8)], library: ["Cinema night", "Sport streaming"] }, visuals: [img(3), img(8)], copy: { headline: "La tua estate in streaming", subheadline: "Film, serie e sport sempre con te.", cta: "Guarda TIMVISION", price: "Promo dedicata", disclaimer: "Catalogo soggetto a variazioni." }, formats: [{ name: "970x250", progress: 100, status: "Approvato", figma: "Figma #TV-EST" }], activity: ["Approvazione marketing ricevuta", "DEM finalizzata"] },
  { id: "camp-004", slug: "tim-wifi-go", name: "TIM WiFi Go", status: "Bozza", updated: "2026-07-08", category: "Product", type: "Product", thumbnail: img(4), shortDescription: "WiFi portatile per vacanze, studio e lavoro fuori casa.", request: "Presentare il WiFi portatile per vacanze e lavoro.", deliverables: ["Banner", "Social"], date: "2026-08-01", attachments: ["moodboard.png"], figma: false, background: "Mobilità e continuità di connessione sono priorità estive.", offer: "Router portatile con giga inclusi.", target: "Viaggiatori, freelance e studenti.", benefits: "Internet condiviso ovunque, setup rapido.", visual: { selected: img(4), variants: [img(4)], library: ["Router viaggio", "Beach desk"] }, visuals: [img(4)], copy: { headline: "Il WiFi ti segue ovunque", subheadline: "Connetti i tuoi dispositivi anche fuori casa.", cta: "Scopri WiFi Go", price: "da 14,99€/mese", disclaimer: "Disponibilità soggetta a verifica." }, formats: [{ name: "1080x1080", progress: 35, status: "Bozza", warning: "Brief incompleto" }], activity: ["Brief creato", "Moodboard caricata"] },
  { id: "camp-005", slug: "business-cloud", name: "TIM Business Cloud", status: "Inviata a Figma", updated: "2026-07-06", category: "Business", type: "Business", thumbnail: img(5), shortDescription: "Lead generation per soluzioni cloud PMI.", request: "Lead generation per soluzioni cloud PMI.", deliverables: ["LinkedIn", "Display"], date: "2026-07-25", attachments: [], figma: true, background: "Le PMI cercano soluzioni cloud semplici e gestite.", offer: "Consulenza e cloud scalabile per aziende.", target: "Decision maker PMI.", benefits: "Sicurezza, supporto e scalabilità.", visual: { selected: img(5), variants: [img(5)], library: ["Cloud team"] }, visuals: [img(5)], copy: { headline: "Cloud semplice per la tua impresa", subheadline: "Soluzioni scalabili con supporto dedicato.", cta: "Richiedi contatto", price: "Su preventivo", disclaimer: "Servizi secondo disponibilità." }, formats: [{ name: "1200x628", progress: 100, status: "Inviato", figma: "Figma #BIZ" }], activity: ["Inviata a Figma"] },
  { id: "camp-006", slug: "summer-giga", name: "Giga Summer", status: "Completata", updated: "2026-06-29", category: "Retention", type: "Retention", thumbnail: img(6), shortDescription: "Upsell pacchetti giga estivi per clienti mobile.", request: "Upsell pacchetti giga estivi.", deliverables: ["App banner", "SMS"], date: "2026-07-01", attachments: ["report.pdf"], figma: true, background: "Aumento consumo dati durante ferie e viaggi.", offer: "Giga extra per l’estate.", target: "Clienti mobile alto consumo.", benefits: "Più navigazione senza cambiare piano.", visual: { selected: img(6), variants: [img(6)], library: ["Summer beach"] }, visuals: [img(6)], copy: { headline: "Più giga per la tua estate", subheadline: "Naviga, condividi e viaggia senza pensieri.", cta: "Aggiungi giga", price: "5€/mese", disclaimer: "Promo valida per clienti selezionati." }, formats: [{ name: "App card", progress: 100, status: "Completato", figma: "Figma #GIGA" }], activity: ["Campagna completata", "Report archiviato"] }
];

export const getCampaignBySlug = (slug: string) => campaigns.find((campaign) => campaign.slug === slug || campaign.id === slug);
export const assets = Array.from({ length: 8 }, (_, i) => ({ id: `asset-${i + 1}`, title: ["Living fibra", "Ritratto mobile", "Cinema night", "Router viaggio", "Cloud team", "Summer beach", "Casa smart", "Sport streaming"][i], campaign: campaigns[i % campaigns.length].name, date: `2026-07-${(15 - i).toString().padStart(2, "0")}`, status: i % 3 === 0 ? "Approvato" : "Variante", tags: ["telco", "adv", i % 2 ? "mobile" : "home"], src: img(i + 1) }));
export const characters = Array.from({ length: 4 }, (_, i) => ({ id: `char-${i + 1}`, name: ["Sara casa smart", "Marco mobile", "Elena business", "Nico streaming"][i], campaigns: i + 1, variants: (i + 2) * 3, status: i % 2 ? "Da approvare" : "Approvato", src: img(i + 11) }));
export const copyItems = Array.from({ length: 10 }, (_, i) => ({ id: `copy-${i + 1}`, text: ["Fibra ultraveloce a 24,90€", "Passa a TIM senza pensieri", "La tua estate in streaming", "Il WiFi ti segue ovunque", "Cloud semplice per la tua impresa", "Più giga per la tua estate", "Connetti casa in pochi giorni", "Intrattenimento per tutta la famiglia", "La rete TIM per il tuo lavoro", "Offerta mobile chiara e flessibile"][i], type: ["Headline", "CTA", "Subheadline", "Disclaimer"][i % 4], campaign: campaigns[i % campaigns.length].name, date: `2026-07-${(12 - i).toString().padStart(2, "0")}`, status: "Approvato", length: 0 })).map(c => ({ ...c, length: c.text.length }));
export const statuses: CampaignStatus[] = ["Bozza", "In lavorazione", "Da approvare", "Approvata", "Inviata a Figma", "Completata"];
