export type CampaignStatus = "Bozza" | "In lavorazione" | "Da approvare" | "Approvata" | "Inviata a Figma" | "Completata";

export type Campaign = {
  id: string;
  slug: string;
  name: string;
  status: CampaignStatus;
  updated: string;
  category: string;
  type: string;
  thumbnail: string;
  shortDescription: string;
  request: string;
  deliverables: string[];
  date: string;
  attachments: string[];
  figma: boolean;
  background: string;
  offer: string;
  target: string;
  benefits: string;
  updatedAt?: string;
  owner?: string;
  priority?: "low" | "medium" | "high";
  offerDescription?: string;
  benefit?: string;
  visual: { selected: string; variants: string[]; library: string[]; origin?: string; approvalStatus?: string };
  visuals: string[];
  copy: { headline: string; subheadline: string; cta: string; price: string; disclaimer: string };
  formats: { name: string; dimensions?: string; progress: number; status: string; warning?: string; figma?: string }[];
  activity: string[];
};

const img = (n: number) => `https://picsum.photos/seed/ultradisplay-${n}/640/420`;

export const campaigns: Campaign[] = [
  { id: "camp-001", slug: "fibra-24-90", name: "Fibra 24,90", status: "In lavorazione", updated: "2026-07-15", updatedAt: "2026-07-15", category: "Acquisition", type: "Acquisition", owner: "Marco", priority: "high", thumbnail: img(1), shortDescription: "Campagna Fibra 24,90 con brief operativo, asset e copy coordinati.", request: "Produrre materiali digitali per Fibra 24,90 con focus conversione e coerenza brand.", deliverables: ['Hero web', 'Display 300x250', 'Stories'], date: "2026-07-21", attachments: ['brief.pdf'], figma: true, background: "Scenario competitivo telco con necessità di messaggi semplici, riconoscibili e ad alto contrasto.", offer: "Offerta Fibra 24,90 con valore immediato e vantaggi chiari per il cliente.", offerDescription: "Offerta Fibra 24,90 con valore immediato e vantaggi chiari per il cliente.", target: "Clienti prospect e base interessati a servizi TIM digitali.", benefits: "Attivazione rapida, affidabilità della rete e supporto guidato.", benefit: "Attivazione rapida, affidabilità della rete e supporto guidato.", visual: { selected: img(1), variants: [img(1), img(13)], library: ["Hero blu", "Lifestyle", "Product focus"], origin: "Libreria UltraDisplay", approvalStatus: "In revisione" }, visuals: [img(1), img(13)], copy: { headline: "Fibra 24,90: il vantaggio TIM", subheadline: "Una proposta chiara, premium e pronta per tutti i formati.", cta: "Scopri di più", price: "da 9,99€/mese", disclaimer: "Offerta soggetta a condizioni e copertura." }, formats: [{ name: "300x250", dimensions: "300×250", progress: 90, status: "Pronto", figma: "Figma #camp-001" }, { name: "1080x1920", dimensions: "1080×1920", progress: 55, status: "In lavorazione", warning: "Verificare safe area" }, { name: "728x90", dimensions: "728×90", progress: 70, status: "Da approvare", figma: "Figma #camp-001-LB" }], activity: ["Brief aggiornato", "Copy revisionato", "Visual selezionato"] },
  { id: "camp-002", slug: "passa-a-tim", name: "Passa a TIM", status: "Da approvare", updated: "2026-07-14", updatedAt: "2026-07-14", category: "Mobile", type: "Mobile", owner: "Elena", priority: "high", thumbnail: img(2), shortDescription: "Campagna Passa a TIM con brief operativo, asset e copy coordinati.", request: "Produrre materiali digitali per Passa a TIM con focus conversione e coerenza brand.", deliverables: ['Social', 'Display', 'DEM'], date: "2026-07-22", attachments: ['moodboard.png', 'listino.xlsx'], figma: false, background: "Scenario competitivo telco con necessità di messaggi semplici, riconoscibili e ad alto contrasto.", offer: "Offerta Passa a TIM con valore immediato e vantaggi chiari per il cliente.", offerDescription: "Offerta Passa a TIM con valore immediato e vantaggi chiari per il cliente.", target: "Clienti prospect e base interessati a servizi TIM digitali.", benefits: "Attivazione rapida, affidabilità della rete e supporto guidato.", benefit: "Attivazione rapida, affidabilità della rete e supporto guidato.", visual: { selected: img(2), variants: [img(2), img(14)], library: ["Hero blu", "Lifestyle", "Product focus"], origin: "Libreria UltraDisplay", approvalStatus: "In revisione" }, visuals: [img(2), img(14)], copy: { headline: "Passa a TIM: il vantaggio TIM", subheadline: "Una proposta chiara, premium e pronta per tutti i formati.", cta: "Scopri di più", price: "da 9,99€/mese", disclaimer: "Offerta soggetta a condizioni e copertura." }, formats: [{ name: "300x250", dimensions: "300×250", progress: 90, status: "Pronto", figma: "Figma #camp-002" }, { name: "1080x1920", dimensions: "1080×1920", progress: 55, status: "In lavorazione", warning: "Verificare safe area" }, { name: "728x90", dimensions: "728×90", progress: 70, status: "Da approvare", figma: "Figma #camp-002-LB" }], activity: ["Brief aggiornato", "Copy revisionato", "Visual selezionato"] },
  { id: "camp-003", slug: "timvision-estate", name: "TIMVISION Estate", status: "Approvata", updated: "2026-07-13", updatedAt: "2026-07-13", category: "Entertainment", type: "Entertainment", owner: "Nico", priority: "medium", thumbnail: img(3), shortDescription: "Campagna TIMVISION Estate con brief operativo, asset e copy coordinati.", request: "Produrre materiali digitali per TIMVISION Estate con focus conversione e coerenza brand.", deliverables: ['Landing', 'Banner', 'App card'], date: "2026-07-23", attachments: ['brief.pdf'], figma: true, background: "Scenario competitivo telco con necessità di messaggi semplici, riconoscibili e ad alto contrasto.", offer: "Offerta TIMVISION Estate con valore immediato e vantaggi chiari per il cliente.", offerDescription: "Offerta TIMVISION Estate con valore immediato e vantaggi chiari per il cliente.", target: "Clienti prospect e base interessati a servizi TIM digitali.", benefits: "Attivazione rapida, affidabilità della rete e supporto guidato.", benefit: "Attivazione rapida, affidabilità della rete e supporto guidato.", visual: { selected: img(3), variants: [img(3), img(15)], library: ["Hero blu", "Lifestyle", "Product focus"], origin: "Libreria UltraDisplay", approvalStatus: "Approvato" }, visuals: [img(3), img(15)], copy: { headline: "TIMVISION Estate: il vantaggio TIM", subheadline: "Una proposta chiara, premium e pronta per tutti i formati.", cta: "Scopri di più", price: "da 9,99€/mese", disclaimer: "Offerta soggetta a condizioni e copertura." }, formats: [{ name: "300x250", dimensions: "300×250", progress: 90, status: "Pronto", figma: "Figma #camp-003" }, { name: "1080x1920", dimensions: "1080×1920", progress: 55, status: "In lavorazione", warning: "Verificare safe area" }, { name: "728x90", dimensions: "728×90", progress: 70, status: "Da approvare", figma: "Figma #camp-003-LB" }], activity: ["Brief aggiornato", "Copy revisionato", "Visual selezionato"] },
  { id: "camp-004", slug: "wifi-go", name: "WiFi Go", status: "Bozza", updated: "2026-07-12", updatedAt: "2026-07-12", category: "Product", type: "Product", owner: "Sara", priority: "medium", thumbnail: img(4), shortDescription: "Campagna WiFi Go con brief operativo, asset e copy coordinati.", request: "Produrre materiali digitali per WiFi Go con focus conversione e coerenza brand.", deliverables: ['Hero web', 'Display 300x250', 'Stories'], date: "2026-07-24", attachments: ['moodboard.png', 'listino.xlsx'], figma: false, background: "Scenario competitivo telco con necessità di messaggi semplici, riconoscibili e ad alto contrasto.", offer: "Offerta WiFi Go con valore immediato e vantaggi chiari per il cliente.", offerDescription: "Offerta WiFi Go con valore immediato e vantaggi chiari per il cliente.", target: "Clienti prospect e base interessati a servizi TIM digitali.", benefits: "Attivazione rapida, affidabilità della rete e supporto guidato.", benefit: "Attivazione rapida, affidabilità della rete e supporto guidato.", visual: { selected: img(4), variants: [img(4), img(16)], library: ["Hero blu", "Lifestyle", "Product focus"], origin: "Libreria UltraDisplay", approvalStatus: "In revisione" }, visuals: [img(4), img(16)], copy: { headline: "WiFi Go: il vantaggio TIM", subheadline: "Una proposta chiara, premium e pronta per tutti i formati.", cta: "Scopri di più", price: "da 9,99€/mese", disclaimer: "Offerta soggetta a condizioni e copertura." }, formats: [{ name: "300x250", dimensions: "300×250", progress: 90, status: "Pronto", figma: "Figma #camp-004" }, { name: "1080x1920", dimensions: "1080×1920", progress: 55, status: "In lavorazione", warning: "Verificare safe area" }, { name: "728x90", dimensions: "728×90", progress: 70, status: "Da approvare", figma: "Figma #camp-004-LB" }], activity: ["Brief aggiornato", "Copy revisionato", "Visual selezionato"] },
  { id: "camp-005", slug: "timvision-days", name: "TIMVISION Days", status: "In lavorazione", updated: "2026-07-11", updatedAt: "2026-07-11", category: "Entertainment", type: "Entertainment", owner: "Marco", priority: "high", thumbnail: img(5), shortDescription: "Campagna TIMVISION Days con brief operativo, asset e copy coordinati.", request: "Produrre materiali digitali per TIMVISION Days con focus conversione e coerenza brand.", deliverables: ['Social', 'Display', 'DEM'], date: "2026-07-25", attachments: ['brief.pdf'], figma: true, background: "Scenario competitivo telco con necessità di messaggi semplici, riconoscibili e ad alto contrasto.", offer: "Offerta TIMVISION Days con valore immediato e vantaggi chiari per il cliente.", offerDescription: "Offerta TIMVISION Days con valore immediato e vantaggi chiari per il cliente.", target: "Clienti prospect e base interessati a servizi TIM digitali.", benefits: "Attivazione rapida, affidabilità della rete e supporto guidato.", benefit: "Attivazione rapida, affidabilità della rete e supporto guidato.", visual: { selected: img(5), variants: [img(5), img(17)], library: ["Hero blu", "Lifestyle", "Product focus"], origin: "Libreria UltraDisplay", approvalStatus: "In revisione" }, visuals: [img(5), img(17)], copy: { headline: "TIMVISION Days: il vantaggio TIM", subheadline: "Una proposta chiara, premium e pronta per tutti i formati.", cta: "Scopri di più", price: "da 9,99€/mese", disclaimer: "Offerta soggetta a condizioni e copertura." }, formats: [{ name: "300x250", dimensions: "300×250", progress: 90, status: "Pronto", figma: "Figma #camp-005" }, { name: "1080x1920", dimensions: "1080×1920", progress: 55, status: "In lavorazione", warning: "Verificare safe area" }, { name: "728x90", dimensions: "728×90", progress: 70, status: "Da approvare", figma: "Figma #camp-005-LB" }], activity: ["Brief aggiornato", "Copy revisionato", "Visual selezionato"] },
  { id: "camp-006", slug: "tim-energia", name: "TIM Energia", status: "Bozza", updated: "2026-07-10", updatedAt: "2026-07-10", category: "Energy", type: "Energy", owner: "Elena", priority: "medium", thumbnail: img(6), shortDescription: "Campagna TIM Energia con brief operativo, asset e copy coordinati.", request: "Produrre materiali digitali per TIM Energia con focus conversione e coerenza brand.", deliverables: ['Landing', 'Banner', 'App card'], date: "2026-07-26", attachments: ['moodboard.png', 'listino.xlsx'], figma: false, background: "Scenario competitivo telco con necessità di messaggi semplici, riconoscibili e ad alto contrasto.", offer: "Offerta TIM Energia con valore immediato e vantaggi chiari per il cliente.", offerDescription: "Offerta TIM Energia con valore immediato e vantaggi chiari per il cliente.", target: "Clienti prospect e base interessati a servizi TIM digitali.", benefits: "Attivazione rapida, affidabilità della rete e supporto guidato.", benefit: "Attivazione rapida, affidabilità della rete e supporto guidato.", visual: { selected: img(6), variants: [img(6), img(18)], library: ["Hero blu", "Lifestyle", "Product focus"], origin: "Libreria UltraDisplay", approvalStatus: "In revisione" }, visuals: [img(6), img(18)], copy: { headline: "TIM Energia: il vantaggio TIM", subheadline: "Una proposta chiara, premium e pronta per tutti i formati.", cta: "Scopri di più", price: "da 9,99€/mese", disclaimer: "Offerta soggetta a condizioni e copertura." }, formats: [{ name: "300x250", dimensions: "300×250", progress: 90, status: "Pronto", figma: "Figma #camp-006" }, { name: "1080x1920", dimensions: "1080×1920", progress: 55, status: "In lavorazione", warning: "Verificare safe area" }, { name: "728x90", dimensions: "728×90", progress: 70, status: "Da approvare", figma: "Figma #camp-006-LB" }], activity: ["Brief aggiornato", "Copy revisionato", "Visual selezionato"] },
  { id: "camp-007", slug: "business-cloud", name: "TIM Business Cloud", status: "Da approvare", updated: "2026-07-09", updatedAt: "2026-07-09", category: "Business", type: "Business", owner: "Nico", priority: "high", thumbnail: img(7), shortDescription: "Campagna TIM Business Cloud con brief operativo, asset e copy coordinati.", request: "Produrre materiali digitali per TIM Business Cloud con focus conversione e coerenza brand.", deliverables: ['Hero web', 'Display 300x250', 'Stories'], date: "2026-07-27", attachments: ['brief.pdf'], figma: true, background: "Scenario competitivo telco con necessità di messaggi semplici, riconoscibili e ad alto contrasto.", offer: "Offerta TIM Business Cloud con valore immediato e vantaggi chiari per il cliente.", offerDescription: "Offerta TIM Business Cloud con valore immediato e vantaggi chiari per il cliente.", target: "Clienti prospect e base interessati a servizi TIM digitali.", benefits: "Attivazione rapida, affidabilità della rete e supporto guidato.", benefit: "Attivazione rapida, affidabilità della rete e supporto guidato.", visual: { selected: img(7), variants: [img(7), img(19)], library: ["Hero blu", "Lifestyle", "Product focus"], origin: "Libreria UltraDisplay", approvalStatus: "In revisione" }, visuals: [img(7), img(19)], copy: { headline: "TIM Business Cloud: il vantaggio TIM", subheadline: "Una proposta chiara, premium e pronta per tutti i formati.", cta: "Scopri di più", price: "da 9,99€/mese", disclaimer: "Offerta soggetta a condizioni e copertura." }, formats: [{ name: "300x250", dimensions: "300×250", progress: 90, status: "Pronto", figma: "Figma #camp-007" }, { name: "1080x1920", dimensions: "1080×1920", progress: 55, status: "In lavorazione", warning: "Verificare safe area" }, { name: "728x90", dimensions: "728×90", progress: 70, status: "Da approvare", figma: "Figma #camp-007-LB" }], activity: ["Brief aggiornato", "Copy revisionato", "Visual selezionato"] },
  { id: "camp-008", slug: "summer-giga", name: "Giga Summer", status: "Approvata", updated: "2026-07-08", updatedAt: "2026-07-08", category: "Retention", type: "Retention", owner: "Sara", priority: "low", thumbnail: img(8), shortDescription: "Campagna Giga Summer con brief operativo, asset e copy coordinati.", request: "Produrre materiali digitali per Giga Summer con focus conversione e coerenza brand.", deliverables: ['Social', 'Display', 'DEM'], date: "2026-07-28", attachments: ['moodboard.png', 'listino.xlsx'], figma: false, background: "Scenario competitivo telco con necessità di messaggi semplici, riconoscibili e ad alto contrasto.", offer: "Offerta Giga Summer con valore immediato e vantaggi chiari per il cliente.", offerDescription: "Offerta Giga Summer con valore immediato e vantaggi chiari per il cliente.", target: "Clienti prospect e base interessati a servizi TIM digitali.", benefits: "Attivazione rapida, affidabilità della rete e supporto guidato.", benefit: "Attivazione rapida, affidabilità della rete e supporto guidato.", visual: { selected: img(8), variants: [img(8), img(20)], library: ["Hero blu", "Lifestyle", "Product focus"], origin: "Libreria UltraDisplay", approvalStatus: "Approvato" }, visuals: [img(8), img(20)], copy: { headline: "Giga Summer: il vantaggio TIM", subheadline: "Una proposta chiara, premium e pronta per tutti i formati.", cta: "Scopri di più", price: "da 9,99€/mese", disclaimer: "Offerta soggetta a condizioni e copertura." }, formats: [{ name: "300x250", dimensions: "300×250", progress: 90, status: "Pronto", figma: "Figma #camp-008" }, { name: "1080x1920", dimensions: "1080×1920", progress: 55, status: "In lavorazione", warning: "Verificare safe area" }, { name: "728x90", dimensions: "728×90", progress: 70, status: "Da approvare", figma: "Figma #camp-008-LB" }], activity: ["Brief aggiornato", "Copy revisionato", "Visual selezionato"] },
  { id: "camp-009", slug: "casa-smart", name: "Casa Smart", status: "Bozza", updated: "2026-07-16", updatedAt: "2026-07-16", category: "Smart Home", type: "Smart Home", owner: "Marco", priority: "medium", thumbnail: img(9), shortDescription: "Campagna Casa Smart con brief operativo, asset e copy coordinati.", request: "Produrre materiali digitali per Casa Smart con focus conversione e coerenza brand.", deliverables: ['Landing', 'Banner', 'App card'], date: "2026-07-20", attachments: ['brief.pdf'], figma: true, background: "Scenario competitivo telco con necessità di messaggi semplici, riconoscibili e ad alto contrasto.", offer: "Offerta Casa Smart con valore immediato e vantaggi chiari per il cliente.", offerDescription: "Offerta Casa Smart con valore immediato e vantaggi chiari per il cliente.", target: "Clienti prospect e base interessati a servizi TIM digitali.", benefits: "Attivazione rapida, affidabilità della rete e supporto guidato.", benefit: "Attivazione rapida, affidabilità della rete e supporto guidato.", visual: { selected: img(9), variants: [img(9), img(21)], library: ["Hero blu", "Lifestyle", "Product focus"], origin: "Libreria UltraDisplay", approvalStatus: "In revisione" }, visuals: [img(9), img(21)], copy: { headline: "Casa Smart: il vantaggio TIM", subheadline: "Una proposta chiara, premium e pronta per tutti i formati.", cta: "Scopri di più", price: "da 9,99€/mese", disclaimer: "Offerta soggetta a condizioni e copertura." }, formats: [{ name: "300x250", dimensions: "300×250", progress: 90, status: "Pronto", figma: "Figma #camp-009" }, { name: "1080x1920", dimensions: "1080×1920", progress: 55, status: "In lavorazione", warning: "Verificare safe area" }, { name: "728x90", dimensions: "728×90", progress: 70, status: "Da approvare", figma: "Figma #camp-009-LB" }], activity: ["Brief aggiornato", "Copy revisionato", "Visual selezionato"] },
  { id: "camp-010", slug: "rete-5g-business", name: "Rete 5G Business", status: "In lavorazione", updated: "2026-07-15", updatedAt: "2026-07-15", category: "Business", type: "Business", owner: "Elena", priority: "high", thumbnail: img(10), shortDescription: "Campagna Rete 5G Business con brief operativo, asset e copy coordinati.", request: "Produrre materiali digitali per Rete 5G Business con focus conversione e coerenza brand.", deliverables: ['Hero web', 'Display 300x250', 'Stories'], date: "2026-07-21", attachments: ['moodboard.png', 'listino.xlsx'], figma: false, background: "Scenario competitivo telco con necessità di messaggi semplici, riconoscibili e ad alto contrasto.", offer: "Offerta Rete 5G Business con valore immediato e vantaggi chiari per il cliente.", offerDescription: "Offerta Rete 5G Business con valore immediato e vantaggi chiari per il cliente.", target: "Clienti prospect e base interessati a servizi TIM digitali.", benefits: "Attivazione rapida, affidabilità della rete e supporto guidato.", benefit: "Attivazione rapida, affidabilità della rete e supporto guidato.", visual: { selected: img(10), variants: [img(10), img(22)], library: ["Hero blu", "Lifestyle", "Product focus"], origin: "Libreria UltraDisplay", approvalStatus: "In revisione" }, visuals: [img(10), img(22)], copy: { headline: "Rete 5G Business: il vantaggio TIM", subheadline: "Una proposta chiara, premium e pronta per tutti i formati.", cta: "Scopri di più", price: "da 9,99€/mese", disclaimer: "Offerta soggetta a condizioni e copertura." }, formats: [{ name: "300x250", dimensions: "300×250", progress: 90, status: "Pronto", figma: "Figma #camp-010" }, { name: "1080x1920", dimensions: "1080×1920", progress: 55, status: "In lavorazione", warning: "Verificare safe area" }, { name: "728x90", dimensions: "728×90", progress: 70, status: "Da approvare", figma: "Figma #camp-010-LB" }], activity: ["Brief aggiornato", "Copy revisionato", "Visual selezionato"] },
  { id: "camp-011", slug: "family-connect", name: "Family Connect", status: "Da approvare", updated: "2026-07-14", updatedAt: "2026-07-14", category: "Family", type: "Family", owner: "Nico", priority: "medium", thumbnail: img(11), shortDescription: "Campagna Family Connect con brief operativo, asset e copy coordinati.", request: "Produrre materiali digitali per Family Connect con focus conversione e coerenza brand.", deliverables: ['Social', 'Display', 'DEM'], date: "2026-07-22", attachments: ['brief.pdf'], figma: true, background: "Scenario competitivo telco con necessità di messaggi semplici, riconoscibili e ad alto contrasto.", offer: "Offerta Family Connect con valore immediato e vantaggi chiari per il cliente.", offerDescription: "Offerta Family Connect con valore immediato e vantaggi chiari per il cliente.", target: "Clienti prospect e base interessati a servizi TIM digitali.", benefits: "Attivazione rapida, affidabilità della rete e supporto guidato.", benefit: "Attivazione rapida, affidabilità della rete e supporto guidato.", visual: { selected: img(11), variants: [img(11), img(23)], library: ["Hero blu", "Lifestyle", "Product focus"], origin: "Libreria UltraDisplay", approvalStatus: "In revisione" }, visuals: [img(11), img(23)], copy: { headline: "Family Connect: il vantaggio TIM", subheadline: "Una proposta chiara, premium e pronta per tutti i formati.", cta: "Scopri di più", price: "da 9,99€/mese", disclaimer: "Offerta soggetta a condizioni e copertura." }, formats: [{ name: "300x250", dimensions: "300×250", progress: 90, status: "Pronto", figma: "Figma #camp-011" }, { name: "1080x1920", dimensions: "1080×1920", progress: 55, status: "In lavorazione", warning: "Verificare safe area" }, { name: "728x90", dimensions: "728×90", progress: 70, status: "Da approvare", figma: "Figma #camp-011-LB" }], activity: ["Brief aggiornato", "Copy revisionato", "Visual selezionato"] },
  { id: "camp-012", slug: "black-friday-fibra", name: "Black Friday Fibra", status: "Approvata", updated: "2026-07-13", updatedAt: "2026-07-13", category: "Promo", type: "Promo", owner: "Sara", priority: "high", thumbnail: img(12), shortDescription: "Campagna Black Friday Fibra con brief operativo, asset e copy coordinati.", request: "Produrre materiali digitali per Black Friday Fibra con focus conversione e coerenza brand.", deliverables: ['Landing', 'Banner', 'App card'], date: "2026-07-23", attachments: ['moodboard.png', 'listino.xlsx'], figma: false, background: "Scenario competitivo telco con necessità di messaggi semplici, riconoscibili e ad alto contrasto.", offer: "Offerta Black Friday Fibra con valore immediato e vantaggi chiari per il cliente.", offerDescription: "Offerta Black Friday Fibra con valore immediato e vantaggi chiari per il cliente.", target: "Clienti prospect e base interessati a servizi TIM digitali.", benefits: "Attivazione rapida, affidabilità della rete e supporto guidato.", benefit: "Attivazione rapida, affidabilità della rete e supporto guidato.", visual: { selected: img(12), variants: [img(12), img(24)], library: ["Hero blu", "Lifestyle", "Product focus"], origin: "Libreria UltraDisplay", approvalStatus: "Approvato" }, visuals: [img(12), img(24)], copy: { headline: "Black Friday Fibra: il vantaggio TIM", subheadline: "Una proposta chiara, premium e pronta per tutti i formati.", cta: "Scopri di più", price: "da 9,99€/mese", disclaimer: "Offerta soggetta a condizioni e copertura." }, formats: [{ name: "300x250", dimensions: "300×250", progress: 90, status: "Pronto", figma: "Figma #camp-012" }, { name: "1080x1920", dimensions: "1080×1920", progress: 55, status: "In lavorazione", warning: "Verificare safe area" }, { name: "728x90", dimensions: "728×90", progress: 70, status: "Da approvare", figma: "Figma #camp-012-LB" }], activity: ["Brief aggiornato", "Copy revisionato", "Visual selezionato"] }
];

export const getCampaignBySlug = (slug: string) => campaigns.find((campaign) => campaign.slug === slug || campaign.id === slug);
export const assets = Array.from({ length: 8 }, (_, i) => ({ id: `asset-${i + 1}`, title: ["Living fibra", "Ritratto mobile", "Cinema night", "Router viaggio", "Cloud team", "Summer beach", "Casa smart", "Sport streaming"][i], campaign: campaigns[i % campaigns.length].name, date: `2026-07-${(15 - i).toString().padStart(2, "0")}`, status: i % 3 === 0 ? "Approvato" : "Variante", tags: ["telco", "adv", i % 2 ? "mobile" : "home"], src: img(i + 1) }));
export const characters = Array.from({ length: 4 }, (_, i) => ({ id: `char-${i + 1}`, name: ["Sara casa smart", "Marco mobile", "Elena business", "Nico streaming"][i], campaigns: i + 1, variants: (i + 2) * 3, status: i % 2 ? "Da approvare" : "Approvato", src: img(i + 11) }));
export const copyItems = Array.from({ length: 10 }, (_, i) => ({ id: `copy-${i + 1}`, text: ["Fibra ultraveloce a 24,90€", "Passa a TIM senza pensieri", "La tua estate in streaming", "Il WiFi ti segue ovunque", "Cloud semplice per la tua impresa", "Più giga per la tua estate", "Connetti casa in pochi giorni", "Intrattenimento per tutta la famiglia", "La rete TIM per il tuo lavoro", "Offerta mobile chiara e flessibile"][i], type: ["Headline", "CTA", "Subheadline", "Disclaimer"][i % 4], campaign: campaigns[i % campaigns.length].name, date: `2026-07-${(12 - i).toString().padStart(2, "0")}`, status: "Approvato", length: 0 })).map(c => ({ ...c, length: c.text.length }));
export const statuses: CampaignStatus[] = ["Bozza", "In lavorazione", "Da approvare", "Approvata", "Inviata a Figma", "Completata"];
