import type { Campaign } from "@/lib/mock-data";
import { EditableField } from "@/components/EditableField";
import { Alert } from "@/components/ui/alert";
import { Card, CardContent } from "@/components/ui/card";

export function CampaignOverview({ campaign }: { campaign: Campaign }) {
  const missing = [!campaign.figma && "Figma da collegare", campaign.formats.some(f => f.warning) && "Warning formati", campaign.visuals.length === 0 && "Visual mancante"].filter(Boolean);
  return <div className="grid gap-4 lg:grid-cols-2"><Card><CardContent className="grid gap-4 p-5 md:grid-cols-2"><EditableField label="Nome" value={campaign.name}/><EditableField label="Stato" value={campaign.status}/><EditableField label="Richiesta" value={campaign.request} long/><EditableField label="Deliverables" value={campaign.deliverables.join(", ")}/><EditableField label="Data" value={campaign.date}/><EditableField label="Allegati" value={campaign.attachments.join(", ") || "Nessun allegato"}/><Alert className="md:col-span-2">{campaign.figma ? "Figma collegato e pronto alla sincronizzazione." : "Figma non collegato per questa campagna."}</Alert></CardContent></Card><Card><CardContent className="space-y-4 p-5"><h3 className="text-lg font-bold">Stato avanzamento</h3><p className="text-sm text-slate-600">{missing.length ? "Campagna incompleta" : "Campagna completa"}</p><div className="rounded-xl bg-blue-50 p-3 text-sm"><b>Contenuti mancanti:</b> {missing.join(", ") || "nessuno"}</div><ul className="space-y-2 text-sm text-slate-600">{campaign.activity.map(item => <li key={item}>• {item}</li>)}</ul></CardContent></Card><div className="grid gap-4 md:grid-cols-2 lg:col-span-2"><EditableField label="Background" value={campaign.background} long/><EditableField label="Descrizione offerta" value={campaign.offer} long/><EditableField label="Target" value={campaign.target} long/><EditableField label="Benefit / Reason Why" value={campaign.benefits} long/></div></div>;
}
